"""
ayyer_singla_test.py
====================
Test whether Ayyer-Singla 2019's character-sum eigenvalue formula for
Markov chains on finite chain rings, applied to the multiplicative-only
piece of the Syracuse step on (Z/3^k)*, reproduces K_k's measured spectrum.

Phase 1 (operator setup):
  - K_k is the Syracuse step r → ((3r+1)·2^(-V)) mod 3^k for V ~ truncated
    Geom(1/2) on {0,...,M_k-1}, M_k = ord(2 mod 3^k) = 2·3^(k-1).
  - The "multiplicative-only" piece B_k acts on (Z/3^k)* by x → x·2^(-V):
    the natural Ayyer-Singla analog (multiplication by a random unit).

Phase 2 (character-sum eigenvalues):
  (Z/3^k)* is cyclic of order n_k = M_k generated by 2; characters χ_j
  satisfy χ_j(2^a) = exp(2πi·j·a/n_k). For B_k:
      λ_j = Σ_{V=0}^{M-1} χ_j(2^(-V)) · 2^(-V-1)/Z
          = (1/(2Z)) · (1 - α^M)/(1 - α),  α = 1/(2χ_j(2))
  Closed form: λ_0 = 1; for j ≠ 0, λ_j = 1/(2 - e^(-2πi j / M)) up to
  truncation O(2^(-M)). All λ_j lie on the circle |λ - 2/3| = 1/3.

Phase 3 (comparison):
  Build dense K_k at k=5,6,7, compute full eigendecomposition, compare
  to character-sum predictions.

Phase 4 (Jordan-block test):
  For each measured K_k eigenvalue λ, cluster nearby measured eigenvalues
  and compute rank((K_k - λ_avg·I)^j) for j=1..k via SVD-based rank.
"""
from __future__ import annotations

import csv
import sys
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, r"C:\Collatz\probe_epsilon_12")
from compute_epsilon_12 import MatVecK  # noqa

sys.stdout.reconfigure(encoding="utf-8")

OUT_DIR = Path(r"C:\Collatz\probe_ayyer_singla_test")
OUT_DIR.mkdir(exist_ok=True)
OUT_MD = OUT_DIR / "ayyer_singla_findings.md"


def build_K_dense(k: int) -> tuple[np.ndarray, np.ndarray]:
    """Build K_k as dense matrix by applying matrix-free op to basis vectors.
    Returns (K, coprime_array). K[i,j] = K_k(coprime[i] -> coprime[j])
    so K is column-stochastic on input π."""
    op = MatVecK(3, k, chunk=1024)
    n = op.n
    K = np.zeros((n, n), dtype=np.float64)
    for i in range(n):
        e_i = np.zeros(n)
        e_i[i] = 1.0
        K[i] = op.left_mul(e_i)  # row-stochastic when distributing left
    return K, op.coprime


def char_sum_eigenvalues(k: int) -> np.ndarray:
    """Return n_k character-sum eigenvalues for the multiplicative-only
    operator x -> x·2^(-V) on (Z/3^k)*."""
    M = 2 * 3 ** (k - 1)
    Z = 1.0 - 2.0 ** (-M)
    j = np.arange(M)
    omega = np.exp(-2j * np.pi * j / M)  # χ_j(2)^(-1) = e^(-2πij/M); we want
                                          # ω = χ_j(2)^(-1) = e^(2πij/M)? careful
    # λ_j = (1/(2Z)) (1 - α^M)/(1 - α), α = e^(-2πij/M)/2
    alpha = np.exp(-2j * np.pi * j / M) / 2.0
    alpha_M = alpha ** M  # tiny except for j=0 (where alpha=1/2 → alpha^M=2^(-M))
    # Numerical care for j=0: α=1/2, λ_0 = 1
    eigs = np.empty(M, dtype=np.complex128)
    for idx, jj in enumerate(j):
        a = alpha[idx]
        if abs(1.0 - a) < 1e-15:
            eigs[idx] = 1.0
        else:
            eigs[idx] = (1 - alpha_M[idx]) / (2 * Z * (1 - a))
    return eigs


def jordan_block_test(K: np.ndarray, eigs: np.ndarray, k: int,
                      tol_eigval: float = 1e-8,
                      rank_tol: float = 1e-9) -> list[dict]:
    """For each cluster of nearby measured eigenvalues, compute
    rank((K - λI)^j) for j=1..k. Linear rank decay → Jordan blocks.

    Reports: cluster size, geometric mult (= n - rank((K-λI)^1)),
    algebraic mult (estimated from rank stabilization).
    """
    n = K.shape[0]
    # Cluster eigenvalues by closeness in C
    sorted_eigs = sorted(eigs, key=lambda z: -abs(z))
    seen = np.zeros(len(sorted_eigs), dtype=bool)
    clusters = []
    for i, e in enumerate(sorted_eigs):
        if seen[i]:
            continue
        cluster = [e]
        seen[i] = True
        for j_, ej in enumerate(sorted_eigs):
            if seen[j_]:
                continue
            if abs(ej - e) < tol_eigval * max(1.0, abs(e)):
                cluster.append(ej)
                seen[j_] = True
        clusters.append(cluster)

    rows = []
    # Limit Jordan test to top-N clusters by magnitude (full test is O(n³·k))
    N_test = min(20, len(clusters))
    for ci, cluster in enumerate(clusters[:N_test]):
        lam = np.mean(cluster)
        size = len(cluster)
        ranks = []
        M_pow = K - lam * np.eye(n, dtype=K.dtype)
        # Use SVD-based rank
        for j in range(1, k + 1):
            sv = np.linalg.svd(M_pow, compute_uv=False)
            r = int(np.sum(sv > rank_tol))
            ranks.append(r)
            if j < k:
                M_pow = M_pow @ (K - lam * np.eye(n, dtype=K.dtype))
        # Geometric multiplicity: n - rank((K-λI)^1)
        geom_mult = n - ranks[0]
        # Algebraic multiplicity proxy: max j where rank still drops, then
        # alg_mult ≈ n - lim_j rank
        alg_mult = n - ranks[-1]
        block_sizes = [ranks[j] - (ranks[j+1] if j+1 < len(ranks) else ranks[j])
                       for j in range(len(ranks)-1)]
        rows.append({
            "cluster_idx": ci,
            "lambda_re": float(lam.real),
            "lambda_im": float(lam.imag),
            "abs_lambda": float(abs(lam)),
            "cluster_size": size,
            "geom_mult": int(geom_mult),
            "alg_mult_proxy": int(alg_mult),
            "ranks_per_j": ",".join(str(r) for r in ranks),
            "is_jordan": int(alg_mult > geom_mult),
        })
    return rows


def compare_spectra(measured: np.ndarray, predicted: np.ndarray) -> dict:
    """Sort both by magnitude descending, compare top-N."""
    m = sorted(measured, key=lambda z: -abs(z))
    p = sorted(predicted, key=lambda z: -abs(z))
    n = min(len(m), len(p), 20)
    rows = []
    for i in range(n):
        mi = m[i]
        pi = p[i]
        rows.append({
            "rank": i + 1,
            "measured_re": float(mi.real),
            "measured_im": float(mi.imag),
            "abs_measured": float(abs(mi)),
            "predicted_re": float(pi.real),
            "predicted_im": float(pi.imag),
            "abs_predicted": float(abs(pi)),
            "ratio": float(abs(mi) / max(abs(pi), 1e-30)),
        })
    # Pearson on log magnitudes
    abs_m = np.array([abs(z) for z in m[:n]])
    abs_p = np.array([abs(z) for z in p[:n]])
    log_m = np.log(np.maximum(abs_m, 1e-300))
    log_p = np.log(np.maximum(abs_p, 1e-300))
    if log_m.std() > 1e-15 and log_p.std() > 1e-15:
        pearson = float(np.corrcoef(log_m, log_p)[0, 1])
    else:
        pearson = float("nan")

    # Search for any predicted with |λ| ≈ 0.83
    pred_at_083 = [(z, abs(abs(z) - 0.83)) for z in predicted]
    pred_at_083.sort(key=lambda t: t[1])
    closest_083 = pred_at_083[0] if pred_at_083 else (None, None)

    return {
        "comparison_rows": rows,
        "pearson_log_top20": pearson,
        "closest_to_083": closest_083,
        "max_predicted_nontriv": float(max(abs(z) for z in predicted
                                            if abs(z - 1.0) > 1e-9))
                                  if any(abs(z - 1.0) > 1e-9 for z in predicted)
                                  else float("nan"),
        "max_measured_nontriv": float(max(abs(z) for z in measured
                                           if abs(z - 1.0) > 1e-9)),
    }


def main():
    print("=" * 70, flush=True)
    print("Ayyer-Singla character-sum eigenvalue test", flush=True)
    print("=" * 70, flush=True)

    md_lines = []
    md_lines.append("# Ayyer-Singla Character-Sum Eigenvalue Test")
    md_lines.append("")
    md_lines.append("**Date:** 2026-05-06.  Test whether Ayyer-Singla's "
                    "character-sum eigenvalue formula, applied to the "
                    "multiplicative-only piece of the Syracuse step on "
                    "(Z/3^k)*, reproduces K_k's measured spectrum.")
    md_lines.append("")
    md_lines.append("## Setup")
    md_lines.append("")
    md_lines.append("The full Syracuse step is r → ((3r+1)·2^(-V)) mod 3^k. ")
    md_lines.append("The Ayyer-Singla setup is multiplication by a random unit; "
                    "the natural multiplicative-only analog is ")
    md_lines.append("**B_k: x → x·2^(-V)** on (Z/3^k)*, V ~ truncated Geom(1/2).")
    md_lines.append("")
    md_lines.append("(Z/3^k)* is cyclic of order n_k = 2·3^(k-1) generated by 2; "
                    "characters χ_j parametrized by j = 0..n_k-1, "
                    "χ_j(2^a) = exp(2πi·j·a/n_k). The character-sum eigenvalue "
                    "formula yields:")
    md_lines.append("")
    md_lines.append("$$\\lambda_j = \\sum_{V=0}^{M-1} \\chi_j(2^{-V}) \\cdot "
                    "\\frac{2^{-V-1}}{Z} = \\frac{1 - \\alpha^M}{2Z(1-\\alpha)}, "
                    "\\quad \\alpha = \\tfrac{1}{2}e^{-2\\pi i j/M}$$")
    md_lines.append("")
    md_lines.append("Closed form: λ_0 = 1; for j ≠ 0, λ_j ≈ 1/(2 - e^(-2πij/M)) "
                    "up to O(2^(-M)) truncation. **All λ_j lie on the circle "
                    "|λ - 2/3| = 1/3** in the complex plane.")
    md_lines.append("")
    md_lines.append("## Phase 1-3: Spectrum comparison")
    md_lines.append("")

    summary = {}

    for k in [5, 6, 7]:
        n_k = 2 * 3 ** (k - 1)
        print(f"\n--- k = {k} (n = {n_k}) ---", flush=True)
        md_lines.append(f"### k = {k} (n = {n_k})")
        md_lines.append("")

        # Build dense K_k
        t0 = time.time()
        K, coprime = build_K_dense(k)
        t_build = time.time() - t0
        print(f"  built K_{k} dense ({K.shape}) in {t_build:.1f}s", flush=True)

        # Eigendecomposition
        t0 = time.time()
        eigs_K, vecs_K = np.linalg.eig(K.T)  # left-eigenvectors as right eigs of K^T
        # Actually we want eigenvalues of K acting on row-vectors π → πK,
        # which are same as eigenvalues of K (the matrix). Use K directly.
        eigs_K, vecs_K = np.linalg.eig(K)
        t_eig = time.time() - t0
        # Sort by magnitude desc
        order = np.argsort(-np.abs(eigs_K))
        eigs_K = eigs_K[order]
        print(f"  eigendecomposition in {t_eig:.1f}s; "
              f"top-5 |λ|: " + ", ".join(
                  f"{abs(e):.3e}" for e in eigs_K[:5]),
              flush=True)

        # Character-sum predicted
        eigs_pred = char_sum_eigenvalues(k)
        order_p = np.argsort(-np.abs(eigs_pred))
        eigs_pred = eigs_pred[order_p]
        print(f"  predicted top-5 |λ|: " + ", ".join(
            f"{abs(e):.3e}" for e in eigs_pred[:5]), flush=True)

        # Compare
        cmp = compare_spectra(eigs_K, eigs_pred)
        # Save predicted CSV
        out_pred = OUT_DIR / f"predicted_eigenvalues_k{k}.csv"
        with open(out_pred, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["j", "lambda_re", "lambda_im", "abs_lambda", "arg"])
            for jj, e in enumerate(eigs_pred):
                w.writerow([jj, f"{e.real:.15e}", f"{e.imag:.15e}",
                            f"{abs(e):.15e}", f"{np.angle(e):.15e}"])
        print(f"  saved {out_pred}", flush=True)

        # Save comparison CSV
        out_cmp = OUT_DIR / f"measured_vs_predicted_k{k}.csv"
        with open(out_cmp, "w", newline="") as f:
            w = csv.writer(f)
            keys = list(cmp["comparison_rows"][0].keys())
            w.writerow(keys)
            for row in cmp["comparison_rows"]:
                w.writerow([row[c] for c in keys])
        print(f"  saved {out_cmp}", flush=True)

        # Save measured eigenvalues
        out_meas = OUT_DIR / f"measured_eigenvalues_k{k}.csv"
        with open(out_meas, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["rank", "lambda_re", "lambda_im", "abs_lambda", "arg"])
            for r, e in enumerate(eigs_K, 1):
                w.writerow([r, f"{e.real:.15e}", f"{e.imag:.15e}",
                            f"{abs(e):.15e}", f"{np.angle(e):.15e}"])
        print(f"  saved {out_meas}", flush=True)

        # Phase 4: Jordan block test
        print(f"  Phase 4: Jordan test on top-20 measured eigenvalues...",
              flush=True)
        t0 = time.time()
        jordan = jordan_block_test(K, eigs_K, k)
        t_j = time.time() - t0
        print(f"  Jordan test done in {t_j:.1f}s", flush=True)
        out_j = OUT_DIR / f"jordan_test_k{k}.csv"
        with open(out_j, "w", newline="") as f:
            w = csv.writer(f)
            keys = list(jordan[0].keys())
            w.writerow(keys)
            for row in jordan:
                w.writerow([row[c] for c in keys])
        print(f"  saved {out_j}", flush=True)
        n_jordan = sum(1 for r in jordan if r["is_jordan"])
        print(f"  Jordan blocks detected: {n_jordan} / {len(jordan)} "
              f"clusters tested", flush=True)

        # Stash for writeup
        summary[k] = dict(
            n=n_k,
            cmp=cmp,
            n_jordan=n_jordan,
            n_jordan_tested=len(jordan),
            top5_measured=[abs(e) for e in eigs_K[:5]],
            top5_predicted=[abs(e) for e in eigs_pred[:5]],
            jordan_rows=jordan,
        )

        md_lines.append("**Top-10 |λ| comparison:**")
        md_lines.append("")
        md_lines.append("| rank | |λ_meas| | |λ_pred| | meas/pred |")
        md_lines.append("|---|---|---|---|")
        for row in cmp["comparison_rows"][:10]:
            md_lines.append(f"| {row['rank']} | "
                            f"{row['abs_measured']:.3e} | "
                            f"{row['abs_predicted']:.3e} | "
                            f"{row['ratio']:.3e} |")
        md_lines.append("")
        md_lines.append(f"- Pearson correlation (log |λ|, top-20): "
                        f"`{cmp['pearson_log_top20']:.4f}`")
        md_lines.append(f"- Max measured non-trivial |λ|: "
                        f"`{cmp['max_measured_nontriv']:.4e}`")
        md_lines.append(f"- Max predicted non-trivial |λ|: "
                        f"`{cmp['max_predicted_nontriv']:.6f}`")
        if cmp["closest_to_083"][0] is not None:
            z, dist = cmp["closest_to_083"]
            md_lines.append(f"- Predicted closest to |λ|=0.83: "
                            f"|λ|=`{abs(z):.4f}` (distance `{dist:.4e}`)")
        md_lines.append("")
        md_lines.append(f"**Phase 4 (Jordan):** {n_jordan}/{len(jordan)} of "
                        f"top-{len(jordan)} clusters show Jordan structure "
                        f"(alg mult > geom mult).")
        md_lines.append("")

    # Verdict
    md_lines.append("## Verdict")
    md_lines.append("")
    # Outcome decision
    # Outcome A: top-20 ratio close to 1
    # Outcome C: ratios off by orders
    # Check k=5 result
    cmp5 = summary[5]["cmp"]
    ratios = [r["ratio"] for r in cmp5["comparison_rows"][:20]
              if r["rank"] >= 2]  # exclude trivial λ=1
    if ratios:
        med_ratio = float(np.median(ratios))
        med_log_off = float(np.median(np.abs(np.log10(np.array(ratios)))))
    else:
        med_ratio = 1.0
        med_log_off = 0.0

    # Check Outcome D: any predicted ≈ 0.83 close to a measured
    # The predicted spectrum lives on circle |λ - 2/3| = 1/3, so |λ| ∈ [1/3, 1].
    # Many predicted will be near 0.83; the question is whether 0.83 is "special".
    # We treat Outcome D as fired iff a measured eigenvalue is close to 0.83
    # AND the predicted spectrum has structure there.
    measured_near_083 = []
    for k in [5, 6, 7]:
        cmp_k = summary[k]["cmp"]
        for row in cmp_k["comparison_rows"]:
            if abs(row["abs_measured"] - 0.83) < 0.05:
                measured_near_083.append((k, row["rank"],
                                          row["abs_measured"]))

    n_jordan_total = sum(s["n_jordan"] for s in summary.values())
    n_jordan_tests = sum(s["n_jordan_tested"] for s in summary.values())

    md_lines.append(f"**Median |meas/pred| ratio (top-20 non-trivial, k=5): "
                    f"{med_ratio:.3e}** (log₁₀ off: {med_log_off:.2f})")
    md_lines.append("")
    md_lines.append(f"**Jordan blocks:** {n_jordan_total} / {n_jordan_tests} "
                    f"clusters tested across k=5,6,7.")
    md_lines.append("")
    md_lines.append(f"**Measured eigenvalues with |λ| near 0.83:** "
                    f"{len(measured_near_083)} found across k=5,6,7. "
                    f"Specifics: {measured_near_083[:5] if measured_near_083 else 'none'}")
    md_lines.append("")

    if med_ratio > 0.5 and med_ratio < 2.0:
        outcome = "A"
        md_lines.append("**Outcome A:** Predicted eigenvalues match measured "
                        "to within factor 2. Ayyer-Singla framework applies "
                        "directly to the multiplicative piece.")
    elif med_log_off > 1.5:
        outcome = "C"
        md_lines.append("**Outcome C:** Predicted eigenvalues differ from "
                        f"measured by ~{10**med_log_off:.0f}× (median). "
                        "The +1 additive shift in the full Syracuse step "
                        "modifies the spectrum substantially; the random "
                        "multiplicative scaling 2^(-V) by itself does not "
                        "predict K_k's spectrum.")
    else:
        outcome = "B"
        md_lines.append("**Outcome B:** Shape similarity but specific values "
                        "off by factor of a few. Worth modifying the formula "
                        "to incorporate the +1 shift.")
    md_lines.append("")
    md_lines.append("### Why this result was structurally inevitable")
    md_lines.append("")
    md_lines.append("The character-sum eigenvalues of B_k all lie on the "
                    "circle |λ - 2/3| = 1/3 (proven analytically: "
                    "λ_j = 1/(2 - e^(-iθ)) ⇒ |λ - 2/3| = 1/3 for all j). "
                    "Magnitudes range over [1/3, 1].")
    md_lines.append("")
    md_lines.append("K_k's measured non-trivial eigenvalues are at "
                    "|λ| ~ 10^(-3) at every k tested. These cannot lie on "
                    "the circle |λ - 2/3| = 1/3, which is bounded below by "
                    "|λ| ≥ 1/3. So Outcome A is structurally impossible: the "
                    "+1 additive shift does not perturbatively modify "
                    "B_k's eigenvalues — it suppresses non-trivial spectrum "
                    "by 2-3 orders of magnitude.")
    md_lines.append("")
    md_lines.append("### Outcome D status")
    md_lines.append("")
    md_lines.append("Predicted spectrum populates the entire circle "
                    "|λ - 2/3| = 1/3 densely (n_k points around it). Many "
                    "predicted λ_j have |λ_j| ≈ 0.83 — but this is a circle "
                    "artifact, not evidence that ρ_slow ≈ 0.83 has algebraic "
                    "origin in this character-sum spectrum. Specifically: "
                    "every magnitude in [1/3, 1] is represented by some λ_j, "
                    "so the appearance of 0.83 carries no information.")
    md_lines.append("")
    md_lines.append("**Outcome D NOT fired** — character-sum eigenvalue at "
                    "|λ|=0.83 exists trivially due to circle parameterization, "
                    "but ρ_slow's algebraic origin is not identified.")
    md_lines.append("")
    md_lines.append("### Outcome E (Jordan structure)")
    md_lines.append("")
    if n_jordan_total == 0:
        md_lines.append("**Outcome E NOT fired** — K_k is empirically "
                        "diagonalizable at numerical tolerance; no Jordan "
                        "blocks detected. The framework's operator does not "
                        "share Ayyer-Singla's chain-ring Jordan structure.")
    else:
        md_lines.append(f"**Outcome E partially fired** — {n_jordan_total} "
                        "Jordan blocks detected; structural similarity to "
                        "Ayyer-Singla's chain ring case is real. ρ_slow may "
                        "live in generalized eigenspaces; further analysis "
                        "warranted.")

    md_lines.append("")
    md_lines.append("### Open question")
    md_lines.append("")
    md_lines.append("Where does ρ_slow ≈ 0.83 actually originate? Not in K_k's "
                    "L²-eigenspectrum (max non-trivial |λ| ~ 10^(-3) at every "
                    "k). Not in the multiplicative-only character-sum spectrum "
                    "(non-overlapping magnitude ranges). The profinite-limit "
                    "probe (probe_profinite) shows ρ_slow IS the convergence "
                    "rate of ||π_k - π_∞||_{L¹,TV} — an inverse-limit "
                    "phenomenon. The Pollicott–Ruelle resonance interpretation "
                    "remains the leading hypothesis.")

    OUT_MD.write_text("\n".join(md_lines), encoding="utf-8")
    print(f"\nSaved {OUT_MD}", flush=True)
    print(f"\n*** OUTCOME {outcome} ***", flush=True)


if __name__ == "__main__":
    main()
