"""
framework_test.py
=================
Test whether the Diaconis-Graham 1992 / CDG / DS-C 1994 Fourier framework
applies to K_k on (Z/3^k)*.

Key prediction (DG framework, iid case): Q̂_n(χ) = F(χ)^n for some F(χ)
independent of (r0, n, ...). Equivalent: the ratio
    F_n(r0, χ) := Q̂_n(χ) / Q̂_{n-1}(χ)
is constant in n and r0.

When the dynamics is X → a·X + ε with shift-invariant transition kernel
on (Z/3^k)*, characters χ are eigenvectors of K and F_n collapses to the
single eigenvalue. K_k = (3X+1)·2^(-V) is NOT shift-invariant: the +1
breaks shift symmetry. The test asks whether the breakage is "small"
(framework applies with modification) or "large" (framework fails).

Phase 1: Compute Q̂_n(χ) = ⟨χ̄, K^n δ_r0⟩ for r0 ∈ several test points,
         χ ∈ all characters of (Z/3^k)*, n=1..10.
Phase 2: Compute F_n(r0, χ) = Q̂_n / Q̂_{n-1}; test stability in n and r0.
Phase 3: Cayley graph diameter and growth for (Z/3^k)*, generators {2, 2^-1}.
Phase 4: Outcome decision.

Output:
  Q_hat_per_character_k{k}.csv
  product_structure_test_k{k}.csv
  moderate_growth_test_k{k}.csv
  framework_findings.md
"""
from __future__ import annotations

import csv
import sys
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, r"C:\Collatz\probe_epsilon_12")
sys.path.insert(0, r"C:\Collatz\probe_ayyer_singla_test")
from compute_epsilon_12 import MatVecK  # noqa
from ayyer_singla_test import build_K_dense  # noqa

sys.stdout.reconfigure(encoding="utf-8")

OUT_DIR = Path(r"C:\Collatz\probe_framework_test")
OUT_DIR.mkdir(exist_ok=True)
OUT_MD = OUT_DIR / "framework_findings.md"

N_STEPS = 10            # iterate K_k up to this many steps
N_R0_TEST = 8           # number of test r0 points
N_CHAR_REPORT = 20      # characters reported in per-character CSV (top by activity)


def char_table(k: int, coprime: np.ndarray) -> np.ndarray:
    """Build characters of cyclic (Z/3^k)* of order n_k = 2·3^(k-1).
    2 is a generator, so characters are χ_j(2^a) = exp(2πi·j·a/n_k).
    Returns chars[j, i] = χ_j(coprime[i]) for j ∈ {0,...,n_k-1}, i ∈ {0,...,n_k-1}.
    """
    N = 3 ** k
    n_k = 2 * 3 ** (k - 1)
    # Build discrete log table: for each coprime r, find a with 2^a = r mod N
    log_table = np.full(N, -1, dtype=np.int64)
    pow2 = 1
    for a in range(n_k):
        log_table[pow2] = a
        pow2 = (pow2 * 2) % N
    a_of_coprime = log_table[coprime]
    assert np.all(a_of_coprime >= 0), "discrete log table incomplete"

    j = np.arange(n_k, dtype=np.float64)
    a = a_of_coprime.astype(np.float64)
    # chars[j, i] = exp(2πi · j · a[i] / n_k)
    chars = np.exp(2j * np.pi * j[:, None] * a[None, :] / n_k)
    return chars  # complex, shape (n_k, n_k)


def cayley_diameter_and_growth(k: int) -> dict:
    """Cayley graph of (Z/3^k)* with generators {2, 2^(-1)}. Group is cyclic
    of order n_k generated by 2 → graph is a cycle of length n_k.
    Distances: d(2^a) = min(a, n_k - a). Growth: V(d) = 2d + 1 (clipped)."""
    n_k = 2 * 3 ** (k - 1)
    diameter = n_k // 2
    # Volume at distances 1, 2, 4, 8, ...
    distances = sorted(set([1, 2, 5, 10, 20, 50, diameter // 4,
                             diameter // 2, diameter]))
    distances = [d for d in distances if 1 <= d <= diameter]
    rows = []
    for d in distances:
        v = min(2 * d + 1, n_k)
        rows.append({"d": d, "V_d": v,
                     "v_over_d_to_1": v / d if d > 0 else 0.0,
                     "v_over_d_squared": v / d ** 2 if d > 0 else 0.0})
    return {
        "k": k,
        "n_k": n_k,
        "diameter": diameter,
        "growth_dim_d": 1,
        "rows": rows,
    }


def main():
    md_lines = []
    md_lines.append("# Diaconis-Graham / DS-C Framework Applicability to K_k")
    md_lines.append("")
    md_lines.append("**Date:** 2026-05-06.  Tests whether DG-1992 product structure "
                    "Q̂_n(χ) = F(χ)^n holds for K_k on (Z/3^k)*.")
    md_lines.append("")
    md_lines.append("## Setup")
    md_lines.append("")
    md_lines.append("(Z/3^k)* is cyclic of order n_k = 2·3^(k-1), generated by 2. "
                    "K_k transition: r → ((3r+1)·2^(-V)) mod 3^k for V ~ truncated "
                    "Geom(1/2). The +1 breaks shift-invariance on (Z/3^k)*; "
                    "characters are NOT eigenvectors of K_k a priori.")
    md_lines.append("")

    summary = {}

    for k in [5, 6, 7]:
        n_k = 2 * 3 ** (k - 1)
        print(f"\n=== k = {k} (n = {n_k}) ===", flush=True)
        md_lines.append(f"### k = {k} (n = {n_k})")
        md_lines.append("")

        t0 = time.time()
        K, coprime = build_K_dense(k)
        print(f"  built dense K_{k} in {time.time()-t0:.1f}s", flush=True)

        # === Phase 1: Q̂_n(χ) ===
        # Compute K^n δ_r0 for several r0, n=0..N_STEPS
        # Then Q̂_n(χ) = sum_x δ_n[x] · conj(χ(x))
        rng = np.random.default_rng(20260506 + k)
        r0_indices = rng.choice(n_k, size=min(N_R0_TEST, n_k), replace=False)
        print(f"  r0 test set ({len(r0_indices)} points): "
              f"{r0_indices[:5]}...", flush=True)

        chars = char_table(k, coprime)  # (n_k, n_k) complex
        # Q_n[r0_idx, n, x] for x in (Z/3^k)*
        Q_n = np.zeros((len(r0_indices), N_STEPS + 1, n_k), dtype=np.float64)
        for ri, r0 in enumerate(r0_indices):
            v = np.zeros(n_k)
            v[r0] = 1.0
            Q_n[ri, 0] = v
            for n in range(1, N_STEPS + 1):
                # left-multiplication: Q^T · K = (K^T · Q)^T
                v = K.T @ v
                Q_n[ri, n] = v

        # Q_hat[r0_idx, n, j] = Σ_x Q_n(x) · conj(χ_j(x))
        # = chars.conj() @ Q_n[r0_idx, n]
        Q_hat = np.einsum('ji,Nni->Nnj', np.conj(chars), Q_n)
        # shape: (n_r0, N_STEPS+1, n_k)
        print(f"  Q̂_n(χ) computed: shape {Q_hat.shape}", flush=True)

        # Save Q̂ for top-N_CHAR_REPORT non-trivial characters by max |Q̂_n(χ)|
        # over n>=1 (averaged over r0)
        activity = np.mean(np.abs(Q_hat[:, 1:, :]), axis=(0, 1))
        # exclude trivial char (j=0): Q̂_n(χ_0) = 1 always
        activity[0] = -1
        top_chars = np.argsort(-activity)[:N_CHAR_REPORT]

        out_qhat = OUT_DIR / f"Q_hat_per_character_k{k}.csv"
        with open(out_qhat, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["r0_idx", "r0", "char_j", "n", "Q_hat_re",
                        "Q_hat_im", "abs_Q_hat"])
            for ri, r0 in enumerate(r0_indices):
                for j in top_chars:
                    for n in range(N_STEPS + 1):
                        z = Q_hat[ri, n, j]
                        w.writerow([ri, int(coprime[r0]), int(j), n,
                                    f"{z.real:.10e}", f"{z.imag:.10e}",
                                    f"{abs(z):.10e}"])
        print(f"  saved {out_qhat}", flush=True)

        # === Phase 2: F_n(r0, χ) = Q̂_n / Q̂_{n-1} ===
        # Test product structure
        F_ratios = np.full(Q_hat.shape, np.nan, dtype=np.complex128)
        for n in range(1, N_STEPS + 1):
            denom = Q_hat[:, n - 1, :]
            num = Q_hat[:, n, :]
            mask = np.abs(denom) > 1e-12
            with np.errstate(divide='ignore', invalid='ignore'):
                F_ratios[:, n, :] = np.where(mask, num / denom, np.nan)

        # For each (r0, χ): variance of F_n across n=2..N_STEPS
        # (start from n=2 because n=1 is undefined ratio Q̂_1 / Q̂_0 with Q̂_0 = δ̂(χ)
        # which is well-defined but special)
        out_prod = OUT_DIR / f"product_structure_test_k{k}.csv"
        with open(out_prod, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow([
                "r0_idx", "r0", "char_j", "abs_F_n_mean",
                "abs_F_n_std", "abs_F_n_cov", "F_n_phase_std_rad",
                "n_valid",
                "F_2_re", "F_2_im", "F_5_re", "F_5_im",
                "F_10_re", "F_10_im",
            ])
            stats = []
            for ri, r0 in enumerate(r0_indices):
                for j in top_chars:
                    Fs = F_ratios[ri, 2:N_STEPS + 1, j]
                    valid = ~np.isnan(Fs)
                    n_valid = int(valid.sum())
                    if n_valid < 3:
                        continue
                    Fs_v = Fs[valid]
                    abs_F = np.abs(Fs_v)
                    abs_mean = float(abs_F.mean())
                    abs_std = float(abs_F.std())
                    cov = abs_std / max(abs_mean, 1e-30)
                    # phase: argument std (use circular)
                    phases = np.angle(Fs_v)
                    # circular std
                    R = abs(np.mean(np.exp(1j * phases)))
                    phase_std = float(np.sqrt(-2 * np.log(max(R, 1e-15))))
                    stats.append({
                        "ri": ri, "j": int(j),
                        "abs_mean": abs_mean, "abs_std": abs_std,
                        "cov": cov, "phase_std": phase_std,
                    })
                    F_2 = F_ratios[ri, 2, j]
                    F_5 = F_ratios[ri, 5, j]
                    F_10 = F_ratios[ri, 10, j]
                    w.writerow([
                        ri, int(coprime[r0]), int(j), f"{abs_mean:.6e}",
                        f"{abs_std:.6e}", f"{cov:.4e}",
                        f"{phase_std:.4e}", n_valid,
                        f"{F_2.real:.6e}" if not np.isnan(F_2) else "",
                        f"{F_2.imag:.6e}" if not np.isnan(F_2) else "",
                        f"{F_5.real:.6e}" if not np.isnan(F_5) else "",
                        f"{F_5.imag:.6e}" if not np.isnan(F_5) else "",
                        f"{F_10.real:.6e}" if not np.isnan(F_10) else "",
                        f"{F_10.imag:.6e}" if not np.isnan(F_10) else "",
                    ])
        print(f"  saved {out_prod}", flush=True)

        # Aggregate stats
        if stats:
            covs = np.array([s["cov"] for s in stats])
            phases = np.array([s["phase_std"] for s in stats])
            cov_median = float(np.median(covs))
            cov_max = float(covs.max())
            phase_median = float(np.median(phases))
            phase_max = float(phases.max())
        else:
            cov_median = cov_max = phase_median = phase_max = float("nan")

        print(f"  product test stats:")
        print(f"    coefficient-of-variation of |F_n| across n:  "
              f"median {cov_median:.3e}, max {cov_max:.3e}")
        print(f"    phase circular std of F_n across n:          "
              f"median {phase_median:.3e}, max {phase_max:.3e}")

        # Compare per-character F (averaged over n) across different r0
        # If Outcome A holds, F̄(χ) should be the same for all r0
        # Compute mean F over n=2..10 per (r0, χ), then std across r0
        F_per_r0_mean = np.full((len(r0_indices), len(top_chars)),
                                 np.nan, dtype=np.complex128)
        for ri in range(len(r0_indices)):
            for jc, j in enumerate(top_chars):
                Fs = F_ratios[ri, 2:N_STEPS + 1, j]
                valid = ~np.isnan(Fs)
                if valid.sum() >= 3:
                    F_per_r0_mean[ri, jc] = Fs[valid].mean()
        # std across r0 (per char)
        r0_disagreement = []
        for jc in range(len(top_chars)):
            col = F_per_r0_mean[:, jc]
            valid = ~np.isnan(col)
            if valid.sum() >= 2:
                m = col[valid].mean()
                disagreement = float(np.std(np.abs(col[valid] - m)))
                r0_disagreement.append(disagreement / max(abs(m), 1e-30))
        if r0_disagreement:
            r0_disagreement_median = float(np.median(r0_disagreement))
            r0_disagreement_max = float(np.max(r0_disagreement))
        else:
            r0_disagreement_median = r0_disagreement_max = float("nan")
        print(f"    F(χ) disagreement across r0 (relative): "
              f"median {r0_disagreement_median:.3e}, "
              f"max {r0_disagreement_max:.3e}")

        # === Phase 3: Cayley graph and growth ===
        cayley = cayley_diameter_and_growth(k)
        out_cayley = OUT_DIR / f"moderate_growth_test_k{k}.csv"
        with open(out_cayley, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["d", "V_d", "V_d/d", "V_d/d^2"])
            for r in cayley["rows"]:
                w.writerow([r["d"], r["V_d"],
                            f"{r['v_over_d_to_1']:.4f}",
                            f"{r['v_over_d_squared']:.4f}"])
        print(f"  saved {out_cayley}", flush=True)
        print(f"  Cayley diameter γ_{k} = {cayley['diameter']}")
        print(f"  growth dim d = {cayley['growth_dim_d']} "
              f"(abelian cyclic; trivially polynomial)")

        # Stash
        summary[k] = {
            "n_k": n_k,
            "cov_median": cov_median,
            "cov_max": cov_max,
            "phase_median": phase_median,
            "phase_max": phase_max,
            "r0_disagree_median": r0_disagreement_median,
            "r0_disagree_max": r0_disagreement_max,
            "cayley": cayley,
            "stats_count": len(stats),
            "top_chars": [int(j) for j in top_chars],
        }

        # Markdown
        md_lines.append("**Phase 1-2: Product structure F_n(r0, χ) = "
                        "Q̂_n / Q̂_{n-1}**")
        md_lines.append("")
        md_lines.append(f"Across n=2..10 (8 ratios) and {N_R0_TEST} test r0 "
                        f"and top {N_CHAR_REPORT} non-trivial characters:")
        md_lines.append("")
        md_lines.append(f"- |F_n| coefficient-of-variation across n:  "
                        f"median {cov_median:.3e}, max {cov_max:.3e}")
        md_lines.append(f"- phase(F_n) circular std across n:          "
                        f"median {phase_median:.3e}, max {phase_max:.3e}")
        md_lines.append(f"- F̄(χ) (avg over n) disagreement across r0: "
                        f"median {r0_disagreement_median:.3e}, "
                        f"max {r0_disagreement_max:.3e}")
        md_lines.append("")
        md_lines.append(f"**Phase 3: Cayley diameter & growth**")
        md_lines.append("")
        md_lines.append(f"- (Z/3^{k})\\* cyclic of order n_k = {n_k}")
        md_lines.append(f"- diameter γ_{k} = n_k / 2 = "
                        f"{cayley['diameter']}")
        md_lines.append(f"- growth dim d = 1 (linear, polynomial, "
                        "trivially moderate)")
        md_lines.append("")

    # === Phase 4: Verdict ===
    md_lines.append("## Verdict")
    md_lines.append("")
    md_lines.append("**Phase 3 (moderate growth)** is trivially confirmed: "
                    "(Z/3^k)\\* is cyclic, generators {2, 2^(-1)} give "
                    "diameter n_k/2 with linear growth d=1. So DS-C 1994's "
                    "moderate-growth precondition holds.")
    md_lines.append("")
    md_lines.append("**Phase 2 (product structure)** is the discriminating "
                    "test. Summary across k=5,6,7:")
    md_lines.append("")
    md_lines.append("| k | |F_n| CoV (n) median | phase std (n) median | r0 disagreement median |")
    md_lines.append("|---|---|---|---|")
    for k in [5, 6, 7]:
        s = summary[k]
        md_lines.append(f"| {k} | {s['cov_median']:.3e} | "
                        f"{s['phase_median']:.3e} | "
                        f"{s['r0_disagree_median']:.3e} |")
    md_lines.append("")

    # Decision logic
    cov_meds = [summary[k]["cov_median"] for k in [5, 6, 7]]
    r0_meds = [summary[k]["r0_disagree_median"] for k in [5, 6, 7]]
    cov_grand_med = float(np.median(cov_meds))
    r0_grand_med = float(np.median(r0_meds))

    if cov_grand_med < 0.01 and r0_grand_med < 0.01:
        outcome = "A"
        md_lines.append("**Outcome A — DG/CDG framework applies directly.** "
                        f"Median |F_n| CoV = {cov_grand_med:.3e} "
                        f"and r0 disagreement = {r0_grand_med:.3e} "
                        "are both below 1%, indicating clean per-character "
                        "product structure with stable F(χ). Combined with "
                        "Phase 3's confirmed polynomial growth, DS-C sharp "
                        "rates apply in principle to K_k.")
    elif cov_grand_med < 0.5 and r0_grand_med < 0.5:
        outcome = "B"
        md_lines.append("**Outcome B — DG/CDG framework applies with "
                        "modification.** Per-character ratios F_n vary "
                        f"with n (CoV {cov_grand_med:.3e}) and across r0 "
                        f"(disagreement {r0_grand_med:.3e}) at moderate "
                        "magnitude — within an order, suggesting a "
                        "trajectory-averaged or path-dependent "
                        "modification of the iid framework would close "
                        "the gap.")
    else:
        outcome = "C"
        md_lines.append("**Outcome C — DG/CDG framework does NOT apply.** "
                        f"Per-character ratios F_n vary widely "
                        f"with n (median CoV {cov_grand_med:.3e}) and "
                        f"across r0 (disagreement {r0_grand_med:.3e}). "
                        "The +1 additive shift in K_k breaks shift "
                        "invariance on (Z/3^k)\\* enough that characters "
                        "are not approximate eigenvectors. The iid "
                        "product structure does not hold even "
                        "approximately.")

    md_lines.append("")
    md_lines.append("### Why this outcome (structural reading)")
    md_lines.append("")
    md_lines.append("DG/CDG product structure Q̂_n(χ) = F(χ)^n requires "
                    "characters χ to be (approximate) eigenvectors of K. "
                    "Equivalent: K must commute with the group action "
                    "(shift-invariance). K_k = (3X+1)·2^(-V) has both "
                    "the deterministic +1 and the deterministic ×3 — the "
                    "+1 breaks shift invariance on (Z/3^k)\\*; the ×3 "
                    "shifts character index. ")
    md_lines.append("")
    md_lines.append("From Probe 3 (Ayyer-Singla test): the multiplicative-"
                    "only operator B_k: x → x·2^(-V) DOES have characters "
                    "as eigenvectors with eigenvalues on |λ - 2/3|=1/3. "
                    "K_k with the +1 destroys this, leaving the "
                    "essentially-non-diagonalizable Jordan-tower structure "
                    "(cond(V) ~ 10^14 → 10^17 across k=5..7).")
    md_lines.append("")
    md_lines.append("### Synthesis")
    md_lines.append("")
    md_lines.append("DG product structure is a property of shift-invariant "
                    "(commutative-with-group-action) Markov kernels. K_k is "
                    "not shift-invariant. The framework's character-Fourier "
                    "diagonalization fails for the same structural reason "
                    "K_k is not diagonalizable (Outcome E from Probe 3): "
                    "the operator's natural function-space structure is "
                    "the Jordan generalized-eigenspace tower, not the "
                    "L²-character basis.")
    md_lines.append("")
    md_lines.append("This does not mean DS-C 1994 sharp rates are unreachable "
                    "— but they would require the *correct* basis "
                    "(generalized eigenvectors / Jordan chains, or the "
                    "inverse-limit transfer-operator basis on Z₃) rather "
                    "than the character basis. Probe_profinite already "
                    "showed ρ_slow ≈ 0.83 IS the inverse-limit convergence "
                    "rate; that's where the rate lives, not in any "
                    "character-Fourier factor of K_k.")

    OUT_MD.write_text("\n".join(md_lines), encoding="utf-8")
    print(f"\n*** OUTCOME {outcome} ***", flush=True)
    print(f"Saved {OUT_MD}")


if __name__ == "__main__":
    main()
