"""
PROBE BRIDGE2 -- Wilson's CORRECTED bridge (2026-07-26). Two fixes: modulus 3^{n+1} (not 3^n); even primitive char.

nu lives on the PRINCIPAL UNITS G_n = (1+3Z)/(1+3^{n+1}Z), cyclic order 3^n, generated by 4. dlog in Z/3^n (= R10's
coord, NOT bespoke). G_n sits mod 3^{n+1}. Character: chi_a^+ = even extension to (Z/3^{n+1})* (trivial on -1);
for 3-nmid a it's PRIMITIVE mod 3^{n+1} so |tau(chibar_a^+)| = sqrt(3^{n+1}). The Z/2 (the +-1 choice) IS the (-1)^a
parity of the D~ bound.

DEGENERATE SANITY (character-only, before any measure): sum_t chibar_a^+(t) e(t/3^{n+1}) = tau(chibar_a^+), |tau|=sqrt(3^{n+1}).
If this fails the character is wrong.

BRIDGE (Y=3W+1, W~forward=R66):  rho-hat(a) = nu_Y-hat(chi_a^+) =?= (1/tau(chibar_a^+)) sum_{t mod 3^{n+1}} chibar_a^+(t) mu_Y(t).
OFFSET (derived): mu_Y(t) = e(t/3^{n+1}) * W-hat(t mod 3^n)  [= the fft(nu)_{k+1}=R66_k offset with a formula].

Also: does stationary_trunc truncate the branch sum (=> recursion normalization mismatch)? Report vm, Z.
"""
import os, sys, time
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from math import gcd
import numpy as np
from probe_27_high_k_rho_q5 import stationary_trunc
from probe_6_conservation_generalize import order_of_two


def main():
    t0 = time.time()
    print("# PROBE BRIDGE2 -- corrected Gauss-sum bridge (mod 3^{n+1}, even primitive char)\n")

    for n in (2, 3, 4, 5):
        q = 3 ** (n + 1); Nn = 3 ** n
        # dlog on G_n = <4> mod q
        DL = {}; g = 1
        for s in range(Nn):
            DL[g] = s; g = (g * 4) % q
        assert len(DL) == Nn, f"G_n not order 3^n: {len(DL)} vs {Nn}"

        def chi(a, t):                      # even primitive character chi_a^+
            tp = t % q
            if tp % 3 == 2:
                tp = (-tp) % q              # principal part (trivial on -1)
            return np.exp(2j * np.pi * a * DL[tp] / Nn)

        ts = [t for t in range(q) if t % 3 != 0]
        eq = np.array([np.exp(2j * np.pi * t / q) for t in ts])

        # --- degenerate/character check: |tau| = sqrt(q) ---
        taus = {}
        for a in (1, 2, 4):
            cb = np.array([np.conj(chi(a, t)) for t in ts])
            taus[a] = np.sum(cb * eq)
        cok = all(abs(abs(taus[a]) - np.sqrt(q)) < 1e-8 for a in taus)
        print(f"## n={n} (q=3^{n+1}={q}): |tau(chibar_a^+)| = "
              f"{', '.join(f'{abs(taus[a]):.4f}' for a in taus)} vs sqrt(q)={np.sqrt(q):.4f}  "
              f"[{'CHAR OK' if cok else 'CHAR WRONG'}]")

        # --- build W (forward=R66), Y=3W+1 ---
        piW, _ = stationary_trunc(3, n)
        cpW = [r for r in range(Nn) if gcd(r, 3) == 1]
        nuW = dict(zip(cpW, piW)); tw = sum(nuW.values()); nuW = {k: v / tw for k, v in nuW.items()}
        nuY = {}
        for W, w in nuW.items():
            Y = (3 * W + 1) % q
            nuY[Y] = nuY.get(Y, 0.0) + w
        tY = sum(nuY.values()); nuY = {k: v / tY for k, v in nuY.items()}

        # W-hat(s) additive mod 3^n ; mu_Y(t) additive mod q ; offset check
        What = {s: sum(w * np.exp(2j * np.pi * s * W / Nn) for W, w in nuW.items()) for s in range(Nn)}
        muY = {t: sum(w * np.exp(2j * np.pi * t * Y / q) for Y, w in nuY.items()) for t in ts}
        off_rel = np.mean([abs(muY[t] - np.exp(2j * np.pi * t / q) * What[t % Nn]) for t in ts]) \
            / (np.mean([abs(muY[t]) for t in ts]) + 1e-30)

        # --- BRIDGE ---
        rels = []
        for a in (1, 2, 4, 5, 7):
            if a % 3 == 0:
                continue
            rho_a = sum(w * chi(a, Y) for Y, w in nuY.items())
            cb = np.array([np.conj(chi(a, t)) for t in ts])
            tau = np.sum(cb * eq)
            rhs = (1.0 / tau) * np.sum(cb * np.array([muY[t] for t in ts]))
            rels.append(abs(rhs - rho_a) / (abs(rho_a) + 1e-30))
        print(f"     offset mu_Y(t)=e(t/q)W-hat(t mod 3^n): rel {off_rel:.2e}  |  "
              f"BRIDGE max rel = {max(rels):.2e}  [{'HOLDS' if max(rels) < 1e-9 else ('close' if max(rels)<1e-4 else 'NO')}]")

    # --- recursion normalization diagnostic ---
    print("\n## stationary_trunc branch-sum truncation (Wilson: mismatch could fake rel~1.3)")
    for n in (3, 4, 5, 6):
        M = order_of_two(3 ** n); vm = min(64, M); Z = 1.0 - 2.0 ** (-M)
        wsum = sum(0.5 ** v / Z for v in range(1, vm + 1))
        print(f"   n={n}: M=ord(2)={M}, vm=min(64,M)={vm}, Z=1-2^-M={Z:.6f}, sum weights={wsum:.9f} "
              f"(vs 1.0; defect {abs(1-wsum):.1e})")
    print("   => if defect ~1e-6 or less, truncation is NOT the rel~1.3 cause (=> fixed-point diagnosis stands).")
    print(f"\n# ({time.time()-t0:.1f}s)")


if __name__ == "__main__":
    main()
